ARG VERSION=11.5.2

FROM grafana/grafana-oss:${VERSION}

# Copy the datasources and dashboard provisioning config
COPY datasources /etc/grafana/provisioning/datasources
COPY dashboards /etc/grafana/provisioning/dashboards

# Create directory for dashboard JSON files (dashboards will be mounted or copied here)
RUN mkdir -p /etc/grafana/dashboards/spin-market